/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GameNewRouteImport } from './routes/game/new'
import { Route as GameGameIdScoreboardRouteImport } from './routes/game/$gameId/scoreboard'
import { Route as GameGameIdEndRouteImport } from './routes/game/$gameId/end'
import { Route as GameGameIdRoundRoundIndexTricksRouteImport } from './routes/game/$gameId/round/$roundIndex/tricks'
import { Route as GameGameIdRoundRoundIndexBidRouteImport } from './routes/game/$gameId/round/$roundIndex/bid'

const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GameNewRoute = GameNewRouteImport.update({
  id: '/game/new',
  path: '/game/new',
  getParentRoute: () => rootRouteImport,
} as any)
const GameGameIdScoreboardRoute = GameGameIdScoreboardRouteImport.update({
  id: '/game/$gameId/scoreboard',
  path: '/game/$gameId/scoreboard',
  getParentRoute: () => rootRouteImport,
} as any)
const GameGameIdEndRoute = GameGameIdEndRouteImport.update({
  id: '/game/$gameId/end',
  path: '/game/$gameId/end',
  getParentRoute: () => rootRouteImport,
} as any)
const GameGameIdRoundRoundIndexTricksRoute =
  GameGameIdRoundRoundIndexTricksRouteImport.update({
    id: '/game/$gameId/round/$roundIndex/tricks',
    path: '/game/$gameId/round/$roundIndex/tricks',
    getParentRoute: () => rootRouteImport,
  } as any)
const GameGameIdRoundRoundIndexBidRoute =
  GameGameIdRoundRoundIndexBidRouteImport.update({
    id: '/game/$gameId/round/$roundIndex/bid',
    path: '/game/$gameId/round/$roundIndex/bid',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/game/new': typeof GameNewRoute
  '/game/$gameId/end': typeof GameGameIdEndRoute
  '/game/$gameId/scoreboard': typeof GameGameIdScoreboardRoute
  '/game/$gameId/round/$roundIndex/bid': typeof GameGameIdRoundRoundIndexBidRoute
  '/game/$gameId/round/$roundIndex/tricks': typeof GameGameIdRoundRoundIndexTricksRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/game/new': typeof GameNewRoute
  '/game/$gameId/end': typeof GameGameIdEndRoute
  '/game/$gameId/scoreboard': typeof GameGameIdScoreboardRoute
  '/game/$gameId/round/$roundIndex/bid': typeof GameGameIdRoundRoundIndexBidRoute
  '/game/$gameId/round/$roundIndex/tricks': typeof GameGameIdRoundRoundIndexTricksRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/game/new': typeof GameNewRoute
  '/game/$gameId/end': typeof GameGameIdEndRoute
  '/game/$gameId/scoreboard': typeof GameGameIdScoreboardRoute
  '/game/$gameId/round/$roundIndex/bid': typeof GameGameIdRoundRoundIndexBidRoute
  '/game/$gameId/round/$roundIndex/tricks': typeof GameGameIdRoundRoundIndexTricksRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/history'
    | '/game/new'
    | '/game/$gameId/end'
    | '/game/$gameId/scoreboard'
    | '/game/$gameId/round/$roundIndex/bid'
    | '/game/$gameId/round/$roundIndex/tricks'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/history'
    | '/game/new'
    | '/game/$gameId/end'
    | '/game/$gameId/scoreboard'
    | '/game/$gameId/round/$roundIndex/bid'
    | '/game/$gameId/round/$roundIndex/tricks'
  id:
    | '__root__'
    | '/'
    | '/history'
    | '/game/new'
    | '/game/$gameId/end'
    | '/game/$gameId/scoreboard'
    | '/game/$gameId/round/$roundIndex/bid'
    | '/game/$gameId/round/$roundIndex/tricks'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HistoryRoute: typeof HistoryRoute
  GameNewRoute: typeof GameNewRoute
  GameGameIdEndRoute: typeof GameGameIdEndRoute
  GameGameIdScoreboardRoute: typeof GameGameIdScoreboardRoute
  GameGameIdRoundRoundIndexBidRoute: typeof GameGameIdRoundRoundIndexBidRoute
  GameGameIdRoundRoundIndexTricksRoute: typeof GameGameIdRoundRoundIndexTricksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/new': {
      id: '/game/new'
      path: '/game/new'
      fullPath: '/game/new'
      preLoaderRoute: typeof GameNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/$gameId/scoreboard': {
      id: '/game/$gameId/scoreboard'
      path: '/game/$gameId/scoreboard'
      fullPath: '/game/$gameId/scoreboard'
      preLoaderRoute: typeof GameGameIdScoreboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/$gameId/end': {
      id: '/game/$gameId/end'
      path: '/game/$gameId/end'
      fullPath: '/game/$gameId/end'
      preLoaderRoute: typeof GameGameIdEndRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/$gameId/round/$roundIndex/tricks': {
      id: '/game/$gameId/round/$roundIndex/tricks'
      path: '/game/$gameId/round/$roundIndex/tricks'
      fullPath: '/game/$gameId/round/$roundIndex/tricks'
      preLoaderRoute: typeof GameGameIdRoundRoundIndexTricksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/$gameId/round/$roundIndex/bid': {
      id: '/game/$gameId/round/$roundIndex/bid'
      path: '/game/$gameId/round/$roundIndex/bid'
      fullPath: '/game/$gameId/round/$roundIndex/bid'
      preLoaderRoute: typeof GameGameIdRoundRoundIndexBidRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HistoryRoute: HistoryRoute,
  GameNewRoute: GameNewRoute,
  GameGameIdEndRoute: GameGameIdEndRoute,
  GameGameIdScoreboardRoute: GameGameIdScoreboardRoute,
  GameGameIdRoundRoundIndexBidRoute: GameGameIdRoundRoundIndexBidRoute,
  GameGameIdRoundRoundIndexTricksRoute: GameGameIdRoundRoundIndexTricksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
